export default function Projects() {
    return (
        <>
            <div>Projects</div>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sit amet tortor non massa scelerisque aliquam placerat vitae mi. Donec varius in erat ac mattis. In quis tristique enim, et scelerisque felis. Cras fermentum nisi in enim posuere venenatis. Donec tortor tellus, malesuada sed pharetra sit amet, suscipit ut eros. Suspendisse sollicitudin turpis vitae tellus volutpat, non egestas felis auctor. Quisque cursus purus nec hendrerit pellentesque. Praesent rutrum eros id sodales maximus. Curabitur ante velit, tincidunt a finibus quis, pretium nec massa. Vivamus nec eros dictum, vulputate risus vel, lacinia tellus. Nunc posuere fermentum tincidunt. Sed faucibus luctus felis, vitae dictum ante sagittis ac.</div>
            <div>Nullam vitae congue elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla urna leo, elementum sed sodales sed, feugiat ac nisi. Fusce consequat, mi id dapibus venenatis, ligula ipsum pellentesque nisi, id bibendum erat dolor sed diam. Nunc eget metus ante. Ut laoreet feugiat turpis, vel efficitur libero mattis quis.</div>
            <div>Suspendisse sollicitudin dui in ligula ultricies auctor. Cras nisi eros, auctor eget convallis ut, convallis nec risus. Nullam sed urna quis augue gravida porta sed faucibus metus. Curabitur dapibus justo massa, quis consectetur est faucibus vehicula. Donec a nulla libero. Pellentesque aliquet vitae nisl ac dictum. Phasellus ac tristique urna. Nulla facilisi. Integer quis metus tincidunt, mollis risus eget, condimentum neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus efficitur nec magna ut suscipit. Suspendisse feugiat mauris id fringilla iaculis. Nullam sem enim, molestie in nulla a, lobortis condimentum metus.</div>
            <div>Phasellus nec dui eget leo lacinia luctus id id libero. Nunc pellentesque, metus nec porttitor mollis, tortor felis pretium elit, sed vehicula magna ex id dui. Vivamus lacinia mi massa, non tristique ante sollicitudin in. Donec molestie sagittis ipsum. Vivamus quis massa mauris. Nam quis urna a quam eleifend tempus ut a lorem. Integer pretium pharetra est tincidunt auctor. Cras nec magna aliquet, dignissim dui et, pretium eros. Vivamus maximus magna at leo dictum pretium. Nunc feugiat cursus euismod. Ut ornare, erat sit amet placerat facilisis, turpis nisi feugiat arcu, et euismod leo ex iaculis nunc. Proin id neque ante. Praesent ut fringilla lorem. Nam iaculis, purus at hendrerit elementum, nisl augue pellentesque sapien, quis sagittis risus lorem a arcu. Vestibulum dui justo, porttitor ac imperdiet vel, viverra quis justo.</div>
            <div>Mauris ullamcorper lacus sodales eros tempor, malesuada feugiat dui interdum. Etiam vitae dui tincidunt, feugiat lectus eu, malesuada dolor. Etiam ut pulvinar orci. Donec sit amet augue erat. Vivamus mi ligula, ullamcorper at metus sit amet, lacinia cursus massa. Pellentesque porta risus quis accumsan tristique. Curabitur augue nulla, vehicula non nisi ac, elementum congue lorem. Etiam sed nunc mi.</div>
            <div>Pellentesque nec neque tempus, volutpat ipsum eu, malesuada dolor. Donec ornare nunc ut rutrum imperdiet. In hac habitasse platea dictumst. Maecenas vitae nisi purus. Donec a leo porttitor, dapibus risus id, sodales ipsum. Donec non elit orci. Vivamus ut accumsan ligula. Nunc eget egestas nisl, nec convallis purus. Quisque ut nunc nibh. Nunc condimentum justo vitae purus consequat pulvinar. Cras eget nisl a dui egestas volutpat quis in leo. Sed leo dui, faucibus ut diam vitae, egestas pretium velit. Sed quam nulla, vestibulum non elit sed, pellentesque euismod lorem. Vivamus et nisl eros. In sagittis vitae tortor quis finibus.</div>
        </>
    )
}