import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "@/components/NavBar";
import Tab from "@/components/Tab";
import Addendum from "@/components/Addendum";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full h-dvh flex flex-col border border-10">
        <NavBar />
        <main className="relative flex flex-col flex-1 min-h-0 overflow-hidden">
          <div className="flex-1 min-h-0">
            <Tab children={children} />
          </div>
          <Addendum />
        </main>
      </body>
    </html>
  );
}
